name: initial test

on:
  push:
    branches: [ "main", "test"]
  pull_request:
    branches: [ "main", "test" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install django
    - name: buildfile command for testproject
      working-directory: ./testproject
      run: |
        djcompiler buildfile
    - name: Compile testproject compile command
      working-directory: ./testproject
      run: |
        djcompiler compile
    - name: Run Tests on Compiled Version
      working-directory: ./testproject/build
      run: |
        python manage.py test
